### ISSUE TITLE
Recovery from lost session Id

### ISSUE THREAD

**Issue by JohnGoyette** [dsimaging/dsio-modality-api#1]
The following information was provided by a development team reviewing the Modality API:

> When a capture session is created, a unique “Session ID” string is automatically generated, and the corresponding sensor is locked (that is, another capture session cannot be initiated with it).  As far as I can tell, the only way to close an active capture session and restore the corresponding device to its original state is by calling the “close” method with the Session ID string.  This means that if the Session ID string is lost before the “close” method can be called (via a crash, for example),  that device remains locked unless the machine is restarted.  Is there a way to query the API for a device’s active capture session ID string?  Is there any way to reset a device to it’s original state, or close a capture session, without access to the ID string?

**Comment by JohnGoyette** [comment]
One way to approach this is to introduce a new API call in the Images API to retrieve all of the currently active sessions. For example, a request like `GET /acquisition` can be used to accomplish this. One concern from a security perspective, is that any authorized client could retrieve all session ids and therefore have direct control over a session even if they did not create it.

To address this concern, I would propose that the `GET /acquisition` API should only return sessions that were created by the same client. The authorization credentials supplied with the request uniquely identify the client. In this way, a client application cannot obtain a session Id that was created by a different client application.

**Comment by JohnGoyette** [comment]
Based on the initial questions quoted in this issue, a typical use case for this feature would involve identifying the session Id for a particular device that is marked as `InUse`. If the intent is to find one `AcquisitionSession`, we can improve the proposed API by adding an optional query parameter, `deviceId`, to filter the sessions based on a device Id. The response would be an array containing exactly one session if the session was found or an empty array if the device was not found to be associated with any currently active session. Of course, the API can still be called without the filter and the client can iterate through the results to filter them for a particular device.

Here is an example of the API call with the optional `deviceId` filter:
` GET /acquisition?deviceId=123456789`

@jtetro2, what do you think of this proposal?

**Comment by JohnGoyette** [comment]
I have updated the OpenAPI spec, Redoc, the Postman collection and the SDK. @jtetro2 , can you please update the Wiki with the new API command?

**Comment by JohnGoyette** [comment]
@jtetro2 ,

The example response for this new API needs to be updated. The `GET /acquisition` API should return an array of AcquisitionSession objects, so the response should be enclosed in square brackets like this:

```
[
  {
    "sessionId": "be362e71-9c18-4f3c-a9ab-d536d7a8b4fd",
    "deviceId": "bc91c079-dabe-0170-1c5e-6ee92b3f4a35",
    "clientName": "OP4 Workstation",
    "createdOn": "11-01-2020",
    "context": {}
  }
]
```

**Comment by jtetro2** [comment]
@JohnGoyette,

Sorry about that. I've corrected it now.

**Comment by JohnGoyette** [comment]
Great! This fix looks good. I am closing this issue.
