### ISSUE TITLE
The Update Acquisition Information should allow enums to be optional properties

### ISSUE THREAD

**Issue by JohnGoyette** [dsimaging/dsio-modality-api#11]
The `Update Acquisition Information` API is a POST method with a body like the following:
```
{
  "enable": true,
  "rotation": 90,
  "binning": "Unbinned",
  "applyLut": true,
  "context": null
}
```

All properties except `context` are _required_. If not supplied the call can still succeed, but the missing properties will be coerced to their default values. This has the possibly unintended side effect of changing rotation (defaults to 0) and binning (defaults to `Unbinned`).

There are use cases when calling this API where the caller may not have enough information or may not want to populate all of these properties. For example, if a sensor is not connected, then `binning` is not relevant. Another example occurs when a caller wants to simply enable or disable acquisition without changing rotation or binning. As for the booleans, `enable` and `applyLut`, these can have suitable defaults that make sense.

I recommend that the `binning` and `rotation` enum properties be changed to _optional_. When not supplied, the API should not alter these properties. This allows callers to ignore the Binning Mode and simply use the sensor default. It also allows users to make multiple calls to the API without changing `rotation` and `binning`.

**Comment by JohnGoyette** [comment]
The OpenAPI spec, Postman collection and Redoc have been updated with nullable enum support for the Rotation and Binning properties of AcquisitionInfo.

**Comment by JohnGoyette** [comment]
@jtetro2 , can you update the Wiki for this issue? 

I have modified the schema for the AcquisitionInfo object with support for nullable enums. The description was updated to reflect this also. We don't call out AcquisitionInfo as a separate model, but it is used in both the `Get Acquisition Information` and the `Update Acquisition Information` APIs. The `Update Acquisition Information` should be updated to reflect these changes. Most likely, we don't need to change anything for the `Get Acquisition Information` API.

**Comment by jtetro2** [comment]
Updated WiKi to reflect these changes.
